# c_example의 makefile
TARGET = infinit limit celsius2fahr fahr2celsius charNumber triangle triangle2 arithmetics increment literal genderRatio compare compare2 sizeof oddeven fourBit test

all : ${TARGET}

infinit : $@
limit : $@
celsius2fahr : $@
fahr2celsius : $@
charNumber : $@
triangle : $@
triangle2 : $@
arithmetics : $@
increment : $@
literal : $@
genderRatio : $@
compare : $@
compare2 : $@
sizeof : $@
oddeven : $@
fourBit : $@
test : $@

clean :
	rm ${TARGET}