# c_example의 makefile
TARGET = test base floatingPoint return1 shutdown shutdown1

all : ${TARGET}

test : $@
base : $@
floatingPoint : $@
return1 : $@
shutdown : $@
shutdown1 : $@

clean :
	rm ${TARGET}