# c_example의 makefile
TARGET = enumExample unionExample charAdress dynamicAllocation fileDiscriptor filePointer strcatExample charPointerOperation helloStr study sumMatrixFunction sumArrayFunction swapFunction arrayCompare arrayAssignment arrayPointer voidPointer functionPoint pointer2 endian pointerConcept qsort bubble swap selection

all : ${TARGET}

enumExample : $@
unionExample : $@
charAdress : $@
dynamicAllocation : $@
fileDiscriptor : $@
filePointer : $@
strcatExample : $@
charPointerOperation : $@
helloStr : $@
study : $@
sumMatrixFunction : $@
sumArrayFunction : $@
swapFunction : $@
arrayCompare : $@
arrayAssignment : $@
arrayPointer : $@
voidPointer : $@
functionPoint : $@
pointer2 : $@
endian : $@
pointerConcept : $@
qsort : $@
bubble : $@
swap : $@
selection : $@


clean :
	rm ${TARGET}