# c_example의 makefile
TARGET = study sumMatrixFunction sumArrayFunction swapFunction arrayCompare arrayAssignment arrayPointer voidPointer functionPoint pointer2 endian pointerConcept qsort bubble swap selection

all : ${TARGET}

study : $@
sumMatrixFunction : $@
sumArrayFunction : $@
swapFunction : $@
arrayCompare : $@
arrayAssignment : $@
arrayPointer : $@
voidPointer : $@
functionPoint : $@
pointer2 : $@
endian : $@
pointerConcept : $@
qsort : $@
bubble : $@
swap : $@
selection : $@


clean :
	rm ${TARGET}