# c_example의 makefile
TARGET = randomTwoInt_copy randomTwoInt one2TenDoWhile one2TenWhile absolute leafYear leafYear_copy passFail grade grade_switch grade_test posZeroNeg posZeroNeg_if posZeroNeg_3 bigLetter one2Ten uninit one2Tensum multiplyTable ascii star

all : ${TARGET}

absolute : $@
leafYear : $@
leafYear_copy : $@
passFail : $@
grade : $@
grade_switch : $@
grade_test : $@
posZeroNeg : $@
posZeroNeg_if : $@
posZeroNeg_3 : $@
bigLetter : $@
one2Ten :$@
uninit : $@
one2Tensum : $@
multiplyTable : $@
ascii : $@
star : $@
one2TenWhile : $@
one2TenDoWhile : $@
randomTwoInt : $@
randomTwoInt_copy : $@

clean :
	rm ${TARGET}