# c_example의 makefile
TARGET = baseball average2022Temp procScore test scoreGrade findMax sumMatrix sumArray dice power returnValue functionSum staticLocalVariable randomTwoInt_copy randomTwoInt one2TenDoWhile one2TenWhile absolute leafYear leafYear_copy passFail grade grade_switch grade_test posZeroNeg posZeroNeg_if posZeroNeg_3 one2Ten uninit one2Tensum multiplyTable ascii star

all : ${TARGET}

baseball : $@
average2022Temp : $@
procScore : $@
test : $@
scoreGrade : $@
findMax : $@
sumMatrix : $@
sumArray : $@
dice : $@
power : $@
returnValue : $@
functionSum : $@
absolute : $@
leafYear : $@
leafYear_copy : $@
passFail : $@
grade : $@
grade_switch : $@
grade_test : $@
posZeroNeg : $@
posZeroNeg_if : $@
posZeroNeg_3 : $@
one2Ten :$@
uninit : $@
one2Tensum : $@
multiplyTable : $@
ascii : $@
star : $@
one2TenWhile : $@
one2TenDoWhile : $@
randomTwoInt : $@
randomTwoInt_copy : $@
staticLocalVariable : $@



clean :
	rm ${TARGET}